baseurl: /
languageCode: en-us
title: Ziemann lab
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
      weight: 1
    - name: Team
      url: /team/
      weight: 2
    - name: Public Data
      url: http://ziemann-lab.net:80/public
      weight: 3
    - name: Rstudio
      url: http://rstudio.ziemann-lab.net
      weight: 4
    - name: Shiny Tools
      url: http://ziemann-lab.net:80/shiny-tools
      weight: 3
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
