---
title: "Appointment to Burnet Institute"
author: "Mark Ziemann"
date: 2023-08-04
categories: ["Careers"]
tags: ["Deakin","Burnet"]
---

After five years at Deakin University I'm excited to announce that
I will take on a new position at Burnet Institue as Head of Bioinformatics.

Deakin has been very good to me and has supported me throughout this time.
At Deakin I was a Lecturer and Senior Lecturer in Biotechnology and
Bioinformatics.
In that role I was teaching primarily into the Masters of Biotechnology
and Bioinformatics course, with some additional undergraduate units.
I completed a Graduate Certificate in Higher Education, which helped me
to become a better teacher.
I also maintained a research group which became increasingly focused
on bioinformatics.
There was a restructure, and I became Course Director of Master of
Biotechnology and Bioinformatics.
At about the same time the course enrolments were paused for an
overhaul of the curriculum and course design which I was deeply
involved in.
Over time, my time was taken up mostly by teaching and administration,
and time for research had a low priority which did not agree with me.

The new role at Burnet is a dream job for me because I feel that my
strengths in teaching, training and supervision can be applied for
maximum benefit to build bioinformatics capacity at this world-leading
institute.
There are organisations that are seeing that data analysis capabilities
are going to be essential to maintaining competitiveness, and those
that invest in this area are going to be at the forefront of what they
do, whether that is in business or research.


